# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Deploy
env:
  OUTPUT_PATH: ${{ github.workspace }}/build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
#    - run: npm test --passWithNoTests
    - name: Package app
      uses: actions/upload-artifact@v1
      with:
        name: reactApp
        path: ${{ env.OUTPUT_PATH }}


  deployApp:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v1
        with:
          name: reactApp
          path: ${{ env.OUTPUT_PATH }}

      - name: "Blob storage upload"
        uses: bacongobbler/azure-blob-storage-upload@v1.0.0
        with:
          source_dir: build
          container_name: www
          connection_string: ${{ secrets.BlobStorageConnectionString }}
